### ISSUE TITLE
Support for Zeebe 1.0.0

### ISSUE THREAD

**Issue by jwulf** [gottfrois/beez#4]
Hi Pierre-Louis, Zeebe 1.0.0 is coming out - it's roughly expected around April. It looks like it will contain a breaking change to the client API. 

The client API change hasn't been merged yet, but I've documented it in [this post](https://forum.zeebe.io/t/changelog-for-zeebe-client-lib-maintainers/2064).

**Comment by vermaxik** [comment]
I can confirm, that with current version of `zeebe-client (0.16.0)` the `beez` gem not compatible.

**Comment by lienvdsteen** [comment]
I've worked on some changes on a forked [repo](https://github.com/lienvdsteen/beez/commits/camunda-cloud). However it's more than just supporting the breaking changes (also added OAuth connection). @gottfrois would you be interested in a PR to this gem or are you not really maintaining this gem anymore? It would definitely need a review since gRPC and Zeebe was all new to me until a couple weeks ago.

**Comment by gottfrois** [comment]
Hey folks,

I'm not actively maintaining the gem but I'll accept PRs for sure :)
The client part was supported by `zeebe-client` gem actually so we should be looking there to update I think.

**Comment by gottfrois** [comment]
Took some time to see what were the changes. I think we can easily support the breaking change in the 1.0.0 API and handle the OAuth authentication @lienvdsteen mentioned in a totally different PR.

**Comment by gottfrois** [comment]
I've quickly merged the following PR in master. I'd like to do a full feature test before bumping the major version number.
https://github.com/gottfrois/beez/pull/15

Might as well spend some time adding specs... finally 😂
